config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users, :controllers => {:omniauth_callbacks => "omniauth_callbacks", :registrations => "registrations"} 
  devise_scope :user do 
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/users/:id', :to => 'users#show', :as => :user
  end
  resources :users
  resources :videos
  resources :images
  resources :reviews
  resources :genres
  resources :categories

  resources :searches do
    get :live_search, on: :collection
    get :category_search, on: :collection
    get :actor_search, on: :collection
  end

  resources :comments do
    get :get_newest, on: :collection
  end
  resources :actors do
     resources :favorite_actors, only: [:create, :destroy]
   end
   
  resources :movies do
    resources :favorite_movies, only: [ :create, :destroy ]
    resources :reviews
    member do
      :reviews
    end
  end

  root 'movies#index'
  get '/search', to: 'searches#new'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user	
	belongs_to :review
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # before_action :set_comment, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  def get_newest
    @comments = Comment.order(id: :desc).limit(8)
    respond_to do |format|
      if @comments
        format.js
      end
    end
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @review = Review.find(params[:review_id])
    @comment = @review.comments.new(comment_params)
    @comment.user_id = params[:user_id]
    respond_to do |format|
      if @comment.save
        # format.html { redirect_to @review }
        # format.json { render :show, status: :created, location: @comment }
        format.js
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:content, :user_id, :review_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :review_id %><br>
    <%= f.text_field :review_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/create.js.erb
$("#new_comment_box").append('<li><b><%= link_to @comment.user.name, @comment.user %> </b>' + "  " + '<%= @comment.content%>' + '<br>' + '<%= @comment.updated_at.to_s %></li>');
// $("#new_comment").html('
//           <% if @comment.user %>
//           <%= link_to( @comment.user.name, @comment.user)%> 
//           <% else %>
//           Anonymous
//           <% end %>
//           <br> 
//           <%= @comment.content%> 
//           ');

$("textarea#comment_content").val("");

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/get_newest.js.erb
// $('#ticker01').html("");
<% @comments.each do |comment|%>
	<% @review = Review.find(comment.review_id) %>
	<% @user = User.find(comment.user_id) %>
	// console.log('<li><a href="<%= review_path(@review)%>"> <%= image_tag("newfeed-icon.jpg")%> <%= @user.name%>: <%= truncate @review.content, length: 30 %>.. </a></li>');
	$('ul#ticker01').append('<li><a href="<%= review_path(@review)%>"> <%= image_tag("newfeed-icon.jpg")%> <%= @user.name%>: <%= truncate comment.content, length: 10 %>.. </a></li>');
<% end %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th>Review</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.content %></td>
        <td><%= comment.user_id %></td>
        <td><%= comment.review_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user_id %>
</p>

<p>
  <strong>Review:</strong>
  <%= @comment.review_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>