config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users, :controllers => {:omniauth_callbacks => "omniauth_callbacks", :registrations => "registrations"} 
  devise_scope :user do 
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/users/:id', :to => 'users#show', :as => :user
  end
  resources :users
  resources :videos
  resources :images
  resources :reviews
  resources :genres
  resources :categories

  resources :searches do
    get :live_search, on: :collection
    get :category_search, on: :collection
    get :actor_search, on: :collection
  end

  resources :comments do
    get :get_newest, on: :collection
  end
  resources :actors do
     resources :favorite_actors, only: [:create, :destroy]
   end
   
  resources :movies do
    resources :favorite_movies, only: [ :create, :destroy ]
    resources :reviews
    member do
      :reviews
    end
  end

  root 'movies#index'
  get '/search', to: 'searches#new'

end

app/models/movie.rb
class Movie < ActiveRecord::Base
	has_many :videos, :dependent => :destroy

	has_many :reviews, :dependent => :destroy
	has_many :movie_categories, :dependent => :destroy
	has_many :categories, :through => :movie_categories

	has_many :movie_genres
	has_many :genres, :through => :movie_genres, :dependent => :destroy

	has_many :movie_producers
	has_many :producers, :through => :movie_producers, :dependent => :destroy

	has_many :movie_actors
	has_many :actors, :through => :movie_actors, :dependent => :destroy

	has_many :favorite_movies
	has_many :users, :through => :favorite_movies, :dependent => :destroy

	
	has_many :images, :dependent => :destroy

	ratyrate_rateable 'score'

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  # before_action :set_movie, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  helper_method :sort_column, :sort_direction
  # GET /movies
  # GET /movies.json
  def index

  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end




  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)
    
    respond_to do |format|
      if @movie.save
       add_genres
       add_categories
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }

      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        add_genres
        add_categories
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }

      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      #params.require(:movie).permit(:name, :score, :ranked, :episodes, :status, :rating, :poster, :summary, :genre_ids => [])
      params.require(:movie).permit(:name, :score, :ranked, :episodes, :status, :rating, :poster, :summary, :genre_ids => [], :category_ids => [])
    end

    def add_genres()
      params[:movie][:genre_ids].each {|genre| 
        count = MovieGenre.where("movie_id = ?", @movie.id).where("genre_id = ?", genre).count
        if count == 0 then MovieGenre.create(:movie_id => @movie.id, :genre_id => genre) 
        end
      }
    end  

       def add_categories()
    # @categories = params[:movie][:categories_name]
       if params[:movie][:category_ids]
       params[:movie][:category_ids].each do |c|
           if not @movie.categories.find(c)
             MovieCategory.create(:movie_id => @movie.id, :category_id => c)
           end
         end
       end
     end
    
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
<% if @movie.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

  <ul>
    <% @movie.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div align="center"> 
  <div class="field">

    <div class="row">
      <div class="col-sm-2">
        <%= label_tag :name, nil, class: "control-label col-sm-2" %>
      </div>
      <div class="col-sm-6">
        <%= f.text_field :name , class: "form-control col-sm-10"%>
      </div>
    </div>
    <br>
     <div class="row">
    <% Genre.all.each do |genre| %>
    <div class="col-md-3" align="left">
      <%= f.check_box :genre_ids, {multiple: true}, genre.id, nil %>
      <%= genre.name %>
      </div>
      <% end %>
    </div>
    <br>

    <div class="row">
      <div class="col-sm-2">
        <%= label_tag :episodes, nil, class: "control-label col-sm-2" %>
      </div>
      <div class="col-sm-2">
        <%= f.number_field :episodes, class: "form-control col-sm-10" %>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-sm-2">
        <%= label_tag :poster, nil, class: "control-label col-sm-2" %>
      </div>
      <div class="col-sm-6">
        <%= f.text_field :poster , class: "form-control col-sm-10"%>
      </div>
    </div>

    <br>
    <div class="row">
      <div class="col-sm-2">
        <%= label_tag :status, nil, class: "control-label col-sm-2" %>
      </div>
      <div class="col-sm-6">
        <%= f.text_field :status , class: "form-control col-sm-10"%>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-sm-2">
        <%= label_tag :summary, nil, class: "control-label col-sm-2" %>
      </div>
      
      <div class="col-sm-6">
        <%= f.text_area :summary, size: "50x5", class: "form-control col-sm-10" %>
      </div>
    </div>
    <br>

    <div class="row">
      <div class="col-sm-2">
      </div>
      <div class="col-sm-6">
        <div id="category-selected">
          <% if @movie %>
            <% @movie.categories.each do |category|%>
              #<%= link_to category.name, category%>
            <% end%>
          <% end%>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-2">
        <%= label_tag :categories, nil, class: "control-label col-sm-2" %>
      </div>
      <div class="col-sm-6">
        <p><%= text_field_tag :q, params[:q], :id =>"categories", :autocomplete => :off, class: "form-control" %></p>
        <div id="category-links" style="display: none"></div>
        <div id="categories-result"></div>
      </div>
      <div class="col-sm-2" id="category-addNew">Add New</div>
    </div>


  <div class="actions">
    <%= f.submit %>
  </div>

</div>
</div>

  <% if @movie %>
    <% @movie.categories.each do |category|%>
      <input type="hidden" name="movie[category_ids][]" value="<%= category.id%>">
    <% end%>
  <% end%>
<% end %>


<script>
$("#categories").bind("keyup", function() {
  var q = $("#categories").val();
  if(q) {
    var url = "/searches/category_search"; // live_search action.   
    $.get(url, {"q": q}, function(response) { // perform an AJAX get
      // all process are within category_search.js.erb
    });
  } else {
    $("#categories-result").css("display", "none");
  }
});

$("div#category-addNew").bind("click", function() {
  var query = $("#categories").val();
  if(query) {
    console.log($("p#category-selection:contains("+ query +")").length);
    if($("p#category-selection:contains("+ query +")").length == 0) {
      // console.log("click");
      var url = "/categories";
      $.post(url, {"category[name]": query}, function(response) {
      });
    }
  }
});

</script>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form' %>


      
<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<!-- <a class="scrollToTop" href="#"><i class="fa fa-angle-up"></i></a> -->
  <% if !params[:order_by]%>
  <div class="col-lg-12 col-md-12 col-sm-12">
    <div class="slick_slider">
      <% @movies = Movie.order('RANDOM()').first(5).each do |movie| %>
      <div class="single_iteam">   <%= link_to (image_tag(movie.poster, alt: "poster")), movie  %>
        <div class="slider_article">
          <h2><%= link_to movie.name, movie, class: "slider_tittle"%></h2>
          <p><%= truncate(movie.summary, :length => 200) %></p>
        </div>
      </div>
      <% end %>

    </div>
  </div>
  <% end %>
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12">
      <div class="left_content">
        <div class="single_post_content">
          <h2><span>Movie</span></h2>
           <% if params[:order_by] && params[:order_by] == 'name' && !params[:commit] %>
          <%@movies = Movie.paginate(page: params[:page], per_page: 3).order(:name)%>
          <%elsif !params[:order_by] && !params[:commit]%>
          <%@movies = Movie.paginate(page: params[:page], per_page: 3).order(id: :desc)%>
          <%elsif params[:commit] == 'Search' %>
          <%@movies = Movie.joins(:movie_genres).where(movie_genres: {genre_id: params[:genre_ids] }).having('count(genre_id) >= ?', params[:genre_ids].count).group("movies.id").paginate(page: params[:page], per_page: 3).order(:id)%>

          <%end%>
          <% @movies.each do |movie| %>
          <ul class="business_catgnav  wow fadeInDown">
            <li>
              <figure class="bsbig_fig"> <a href="<%= movie %>" class="featured_img">  <%= link_to (image_tag(movie.poster, alt: "poster", height: "500")), movie  %>
                <span class="overlay"></span> </a>
                <figcaption> <%= link_to(movie.name, movie) %></figcaption>

                <p><%= truncate(movie.summary, :length => 200) %></p>
                
                <% @review = movie.reviews.last %>
                <% if @review %>
                <p>Latest Review</p>
                 <%= @review.content.scan(/\S+/)[0..100].join(' ').html_safe%>...<%= link_to("See more", @review) %>
                  <% end %>
              </figure>
            </li>
            <li>
              <hr>
            </li>
          </ul>
          <% end %>
          <%= will_paginate %>
        </div>
      </div>
    </div>
  </div>

  

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form' %>

app/views/movies/show.html.erb
<div class="single_page">
  <ol class="breadcrumb">
    <li><%= link_to('Home', root_path) %></li>
    <li class="active"><%= @movie.name %></li>
    <li><%= link_to('Reviews', movie_reviews_path(@movie)) %></li>
  </ol>
  <%= link_to 'Edit', edit_movie_path(@movie) if can? :edit, Movie %>
  <%= link_to 'Destroy', @movie, method: :delete, data: { confirm: 'Are you sure?' } if can? :edit, Movie %>
  <div class="movie_header col-lg-12 col-md-12 col-sm-12">
    <div class="col-lg-8 col-md-8 col-sm-8">
      <div class="left_content">
        <div class="movie_title col-lg-12 col-md-12 col-sm-12">
        <div class=" movie_poster col-lg-3 col-md-3 col-sm-3">
             <%= link_to (image_tag(@movie.poster, alt: "poster", class: "poster")), @movie  %>
        
          </div>
          <div class="col-lg-9 col-md-9 col-sm-9"> <%= @movie.name %></div>
        </div>
        <% @array = @movie.genres.all %>
        <div class="movie_sum col-lg-12 col-md-12 col-sm-12">
          <p><% @array.each do |genre| %>

            <% if genre.name != @array.last.name %>

            <%= link_to genre.name, genre%>,
            <% else %>
            <%= link_to genre.name, genre%>.
            <% end %>
            <% end %>
          </p>
          <p><% @movie.summary.split(/\n/).each do |paragraph| %>
         <%= paragraph %><br>
        <% end %>
         </p>
        </div>

      </div>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-4">
      <aside class="right_content">
        <div class="single_sidebar">
          <div class="movie_score">
            Score: <%= @movie.average("score") ? number_with_precision(@movie.average("score").avg, :precision => 1) : "N/A"%><br>
            <% if current_user %>
            <% rating = Rate.find_by_rater_id_and_rateable_id_and_dimension(current_user.id, @movie.id, "score") %>
            Your Score: 
            <% if rating %>
            <%= rating_for_user @movie, current_user, "score" %>
            <% else %>
            <%= rating_for @movie, "score", disable_after_rate: true, target: '#hintDiv' %>
            <% end %>
            <%= link_to 'Add Review', new_movie_review_path(@movie)%>
            <div id = 'hintDiv'></div>
            <% end %>
          </div>
        </div>

        <% if current_user %>
        <div class="fav">
          <input type="hidden" id="movie_id" value="<%= @movie.id%>">
          <input type="hidden" id="user_id" value="<%= current_user.id %>">
          <% if not FavoriteMovie.find_by(user_id: current_user.id, movie_id: @movie.id) %>
            <input type="hidden" id="favorited_id" value="">
            <button class="btn btn-success" id="favorite">Favorite</button>
          <% else %>
            <input type="hidden" id="favorited_id" value="<%= FavoriteMovie.find_by(user_id: current_user.id, movie_id: @movie.id).id %>">
            <button class="btn btn-success" id="favorite">Favorited</button>
          <% end %>
        </div>
        <%end%>
      </aside>
    </div>
  </div>

  <div class="movie_gallery col-lg-12 col-md-12 col-sm-12">
    <div class="movie_video">
      <div class="col-lg-6 col-md-6 col-sm-6">
        <div class="left_content">
         <h2>Video</h2>
          <%= link_to "Add new video", new_video_path(@movie) if can? :create, Movie %>

         <div class="slick_slider">
         <% if @movie.videos.count != 0 %>
           <%@movie.videos.each do |video| %>
             <% if @movie.videos.exists? %>
               <div class="single_iteam">
               <p><iframe width="300" height="200" src="<%= video.link %>"></iframe></p>
                </div>
             <% end %>
           <% end %>
           <% else %>
           <p>This Video is unavailable</p>  
         <% end %>
         </div>
       </div>
     </div>
   </div>
   <div class="movie_pics">
    <div class="col-lg-6 col-md-6 col-sm-6">
      <aside class="right_content">
       <h2>Picture</h2>
       <%= link_to "Add new image", new_image_path(@movie, :imgtype => 'movie') if can? :create, Movie %>

       <div class="slick_slider">
        <% if @movie.images.count != 0 %>
           <%@movie.images.each do |image| %>
             <% if @movie.images.exists? %>
               <div class="single_iteam">
               <%= image_tag(image.link, alt: "image", height:200, width:300) %>
                </div>
             <% end %>
           <% end %>
           <% else %>
           <p>This Image is unavailable</p>  
         <% end %>
      </div>
    </aside>
  </div>
</div>
</div>
  <h1>Categories</h1><br><br>
 <% @movie.categories.all.each do |category| %>
  <button class="btn btn-theme"><%= link_to category.name, category %></button>
    <% end %>
    <br><br>
<div class="movie_cast col-lg-12 col-md-12 col-sm-12">
  <h1>Cast</h1>
  <div class="movie_actor">
    <div class="col-lg-6 col-md-6 col-sm-6">
      <div class="left_content">
        <h2>Actor</h2>
        <%= link_to "Add new actor", new_actor_path(@movie, :type => "add_role") if can? :create, Movie %>
        <br>
        <% @actor = @movie.actors.order(:id).all %>
        <% @actor.each do |actor| %>
        <%= link_to actor.name, actor %>
        <br>
        <% end %>
      </div>
    </div>
  </div>
  <div class="movie_role">
    <div class="col-lg-6 col-md-6 col-sm-6">
      <aside class="right_content">
      <br>
        <h2>Role</h2>
       <% @role = MovieActor.where("movie_id = ?", @movie.id).order(:actor_id).all.each do |role| %>
       <%= role.role %>
       <br>
       <% end %>
      </aside>
    </div>
  </div>
</div>

<% if !@movie.reviews.empty? %>
<h3>Latest reviews</h3>
<% rs = @movie.reviews.last(3) %>
<% rs.each do |r| %>
<div class="single_review col-lg-12 col-md-12 col-sm-12">
  
  <% rating = Rate.find_by_rater_id_and_rateable_id_and_dimension(r.user_id, @movie.id, "score") %> 
  <%= rating_for_user @movie, User.find(r.user_id), "score" %>
   <p><% r.content.scan(/\S+/)[0..100].join(' ').split(/\n/).each do |paragraph| %>
         <%= paragraph.html_safe %><br>
         <% end %>
   </p>
  
  <p>Reviewed by <%= link_to(get_user_name(r.user_id),  @curr) + " on " + r.updated_at.to_s %></p>
  <p><%= link_to("See more", r) %></p>
</div>
<% end %>
<% else %>
<h1>Don't have any review</h1>
<% end %>
 <% if current_user %>
<%= link_to 'Add Review', new_movie_review_path(@movie)%>
<% end %>
</div>


<script>
$("#favorite").bind("click", function() {
  console.log("favorite clicked");
  if($(this).text() == "Favorite") {
    var user_id = $("#user_id").val();
    var movie_id = $("#movie_id").val();
    var url = movie_id+"/favorite_movies";
    var favorite_movie = {"user_id": user_id, "movie_id": movie_id};
    // var data = {favorite_movie["user_id"]: user_id, favorite_movie["movie_id"]: movie_id};
    // console.log(favorite_movie);
    $.post(url, favorite_movie, function(response) {

    });
  }
  if($(this).text() == "Favorited") {
    console.log("favorited clicked");
    // var user_id = $("#user_id").val();
    var movie_id = $("#movie_id").val();
    var favorited_id = $("#favorited_id").val();
    var url = movie_id+"/favorite_movies/"+ favorited_id;
    // var favorite_movie = {"user_id": user_id, "movie_id": movie_id};
    var favorited = {"id": favorited_id}
    // var data = {favorite_movie["user_id"]: user_id, favorite_movie["movie_id"]: movie_id};
    // console.log(favorite_movie);
    // $.post(url, favorite_movie, function(response) {
    // });
    $.ajax({
      url: url,
      type: 'DELETE',
      data: favorited,
      success: function(result) {

      }
    });
  }

});                                                                                      

</script>