config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users, :controllers => {:omniauth_callbacks => "omniauth_callbacks", :registrations => "registrations"} 
  devise_scope :user do 
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/users/:id', :to => 'users#show', :as => :user
  end
  resources :users
  resources :videos
  resources :images
  resources :reviews
  resources :genres
  resources :categories

  resources :searches do
    get :live_search, on: :collection
    get :category_search, on: :collection
    get :actor_search, on: :collection
  end

  resources :comments do
    get :get_newest, on: :collection
  end
  resources :actors do
     resources :favorite_actors, only: [:create, :destroy]
   end
   
  resources :movies do
    resources :favorite_movies, only: [ :create, :destroy ]
    resources :reviews
    member do
      :reviews
    end
  end

  root 'movies#index'
  get '/search', to: 'searches#new'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :movie_categories
	has_many :movies, :through => :movie_categories, :dependent => :destroy
end

app/models/movie.rb
class Movie < ActiveRecord::Base
	has_many :videos, :dependent => :destroy

	has_many :reviews, :dependent => :destroy
	has_many :movie_categories, :dependent => :destroy
	has_many :categories, :through => :movie_categories

	has_many :movie_genres
	has_many :genres, :through => :movie_genres, :dependent => :destroy

	has_many :movie_producers
	has_many :producers, :through => :movie_producers, :dependent => :destroy

	has_many :movie_actors
	has_many :actors, :through => :movie_actors, :dependent => :destroy

	has_many :favorite_movies
	has_many :users, :through => :favorite_movies, :dependent => :destroy

	
	has_many :images, :dependent => :destroy

	ratyrate_rateable 'score'

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all.paginate(page: params[:page], per_page: 10)
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    set_category
    @movies = @category.movies.paginate(page: params[:page], per_page: 10)
  end

  # GET /categories/new
  def new
    check_access
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        # format.html { redirect_to @category, notice: 'Category was successfully created.' }
        # format.json { render :show, status: :created, location: @category }
        format.js
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end

        def check_access
        if !current_user || current_user.role == "Regular"
        redirect_to root_path, notice: "Access denied"
      end
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/create.js.erb
var count = $("#category-selected a").length;
var url = "<%= category_path @category %>";
console.log(url);
$("#category-selected").append('#<a href="'+ url +'" name="movie[categories]['+ count +']">'+ "<%= @category.name%>"+'</a>');
$('<input>').attr('type', 'hidden').attr('name', 'movie[category_ids][]').attr('value', "<%= @category.id%>").appendTo('form'); 

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<table class="table">
  <thead>
    <tr>
      <th> ID </th>
      <th> Name </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td> <%= category.id%></td>
        <td> <%= category.name%></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) if can? :create, Movie%></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } if can? :create, Movie%></td>
      </tr>
    <% end %>
  </tbody>
</table>
 <%= will_paginate %>
<br>

<%= link_to 'New Category', new_category_path if can? :create, Movie%>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>


<p id="notice"><%= notice %></p>
<h1><%= '#' + @category.name %></h1>
<% @movies.each do |movie|%>
<div class="movies_short_index col-lg-12 col-md-12 col-sm-12">
	<div class=" movie_poster col-lg-2 col-md-2 col-sm-2">
        <%=image_tag(movie.poster, alt: "poster", class: "poster")%>
      </div>
      <div class="col-lg-10 col-md-10 col-sm-10"> 
        <h3><%= link_to(movie.name, movie) %></h3>
        <p><%= movie.summary.scan(/\S+/)[0..25].join(' ') + '...'%>
        </p>
        <% @array = movie.genres.all %>
        <p><% @array.each do |genre| %>
          <% if genre.name != @array.last.name %>
          <%= link_to genre.name, genre%>, 
          <% else %>
          <%= link_to genre.name, genre%>.
          <% end %>
          <% end %>
        </p>
        <p>
          <% movie.categories.each do |category| %>
          <%= link_to '#'+category.name, category%>
          <%end%>
        </p>
      </div>
</div>
<% end%>